export const LOAD_MERCHANTS_SUCCESS = 'LOAD_MERCHANTS_SUCCESS';
export const CREATE_MERCHANTS_SUCCESS = 'CREATE_MERCHANTS_SUCCESS';
export const UPDATE_MERCHANTS_SUCCESS = 'UPDATE_MERCHANTS_SUCCESS';
export const DELETE_MERCHANTS_SUCCESS = 'DELETE_MERCHANTS_SUCCESS';
export const BEGIN_AJAX_CALL = 'BEGIN_AJAX_CALL';
export const AJAX_CALL_ERROR = 'AJAX_CALL_ERROR';